# Generated by Django 5.0.1 on 2024-01-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_company_lead_contact_date_lead_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='phoned_at',
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('phone', 'Phone'), ('social_network', 'Social Networks'), ('tv', 'Tv')], default='open', max_length=200),
        ),
    ]
