# Generated by Django 5.0.1 on 2024-01-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_phoned_at_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('phone', 'Phone'), ('social_network', 'Social Networks'), ('tv', 'Tv')], default='Phone', max_length=200),
        ),
    ]
