# Generated by Django 5.0.1 on 2024-01-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_lead_company_remove_lead_phoned'),
        ('organizations', '0003_company_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organizations.company'),
        ),
    ]
