# Generated by Django 5.0.1 on 2024-01-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_lead_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company',
        ),
    ]
