# Generated by Django 5.0.1 on 2024-01-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='contact_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='product',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='updated_at',
        ),
    ]
