# Generated by Django 4.1.3 on 2023-09-26 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deal_label", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "deal_message",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "end_date",
                    models.DateField(
                        default=datetime.datetime(
                            2023,
                            10,
                            6,
                            12,
                            34,
                            46,
                            832759,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("won", "Won"), ("lost", "Lost")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "custom_field_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "custom_field_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
