# Generated by Django 4.1.3 on 2023-09-26 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 6, 12, 48, 25, 464368, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
