# Generated by Django 5.0.1 on 2024-01-11 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_alter_deal_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 21, 2, 42, 37, 597949, tzinfo=datetime.timezone.utc)),
        ),
    ]
