# Generated by Django 5.0.1 on 2024-01-14 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_alter_deal_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 24, 13, 2, 14, 961211, tzinfo=datetime.timezone.utc)),
        ),
    ]
