# Generated by Django 5.0.1 on 2024-01-14 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0022_alter_deal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 1, 24, 14, 40, 11, 876036, tzinfo=datetime.timezone.utc)),
        ),
    ]
