# Generated by Django 5.0.1 on 2024-01-14 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0023_alter_deal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deadline',
            field=models.DateField(default=datetime.timedelta(days=10)),
        ),
    ]
