# Generated by Django 4.2.3 on 2023-09-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_company_lead_contact_date_lead_created_at_and_more'),
        ('contacts', '0002_alter_contacts_product'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
